{{- if .Values.ingressRoute.enabled -}}
{{- if .Values.linkerd.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "..linkerd-middleware-name" $ }}
spec:
  headers:
    customRequestHeaders:
      l5d-dst-override: "{{ .Values.linkerd.host }}"
---
{{- end }}

{{- range .Values.middlewares }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .name }}
spec:
  {{- toYaml .spec | nindent 2 }}
---
{{- end }}
{{- end }}