name: Build release from tag
on:
  push:
    tags:
      - 'v*.*.*'

env:
  ko_version: 0.17.1

jobs:
  publish_github:
    name: Build latest and publish to ghcr
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Get version from tags
        id: version
        run: echo "tag=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Build
        env:
          CGO_ENABLED: 0
        run: go build -v .

      - name: Install KO
        run: |
          curl -L https://github.com/google/ko/releases/download/v${{ env.ko_version }}/ko_${{ env.ko_version }}_Linux_x86_64.tar.gz | tar xzf - ko
          chmod +x ./ko
      - name: Publish docker image
        env:
          KO_DOCKER_REPO: ghcr.io/${{ github.repository_owner }}
          CGO_ENABLED: 0
        run: |
          ./ko login ghcr.io --username $GITHUB_REPOSITORY_OWNER --password ${{ secrets.GITHUB_TOKEN }}
          ./ko build -B --tags ${{ steps.version.outputs.tag }} .